"""
MX-6 Bridge — Next Attack: Does PSL(2,7) uniquely determine the G₂ 3-form?

If dim(Λ³ℝ⁷)^{PSL(2,7)} = 1, then PSL(2,7) uniquely pins down φ up to scale,
and the 168 identity IS the bridge between information geometry and G₂.

Author: Martin Luther Graise / C-7RO
Date: April 11, 2026
"""

import numpy as np
from itertools import permutations

print("=" * 70)
print("PSL(2,7) BRIDGE TEST: Does the full Fano automorphism group")
print("uniquely determine the G₂ 3-form?")
print("=" * 70)

# ================================================================
# PART 1: Build PSL(2,7) as permutations of {0,...,6}
# ================================================================
print("\n--- PART 1: Constructing PSL(2,7) ⊂ S₇ ---\n")

# PSL(2,7) acts on P¹(F₇) = {0,1,2,3,4,5,6} via Möbius transformations
# x ↦ (ax+b)/(cx+d) mod 7, where ad-bc ≡ 1 mod 7 (up to ±I)
# 
# We generate all such permutations

def moebius_perm(a, b, c, d, p=7):
    """Compute the permutation of {0,...,p-1} induced by x -> (ax+b)/(cx+d) mod p"""
    perm = []
    for x in range(p):
        denom = (c * x + d) % p
        if denom == 0:
            # x maps to "infinity" — but we're on P¹(F₇) with 8 points
            # For the 7-point action, we need to handle this differently
            return None  # This transformation doesn't give a valid 7-point perm
        numer = (a * x + b) % p
        perm.append((numer * pow(denom, p - 2, p)) % p)
    return tuple(perm)

# Generate all elements of PSL(2,7) acting on F₇ = {0,...,6}
# These are the affine transformations x ↦ ax + b with a ∈ F₇*, b ∈ F₇
# PLUS the non-affine Möbius transformations
# Actually, PSL(2,7) acting on P¹(F₇) has 8 points. To get a 7-point
# action, we use the action on the 7 LINES of the Fano plane,
# or equivalently, we use the 7-dimensional representation.

# Simpler approach: generate PSL(2,7) as a permutation group on 7 points
# using known generators.
# 
# Standard generators of PSL(2,7) acting on {0,...,6}:
# α = (0 1 2 3 4 5 6)  [7-cycle, corresponding to x ↦ x+1]
# β = (1 2 4)(3 6 5)    [order 3, corresponding to x ↦ 2x]

def apply_perm(perm, x):
    return perm[x]

def compose(p1, p2):
    """Compose permutations: first apply p2, then p1"""
    return tuple(p1[p2[i]] for i in range(len(p1)))

def perm_power(p, n):
    result = tuple(range(len(p)))
    base = p
    n = n % perm_order(p) if n > 0 else n
    for _ in range(n):
        result = compose(result, base)
    return result

def perm_order(p):
    current = p
    identity = tuple(range(len(p)))
    for i in range(1, 200):
        if current == identity:
            return i
        current = compose(current, p)
    return -1

def inverse_perm(p):
    inv = [0] * len(p)
    for i, v in enumerate(p):
        inv[v] = i
    return tuple(inv)

# Generators
alpha = (1, 2, 3, 4, 5, 6, 0)  # x ↦ x+1 mod 7
beta = tuple([0, 2, 4, 6, 1, 3, 5])  # x ↦ 2x mod 7

print(f"Generator α = {alpha}  (x ↦ x+1 mod 7, order {perm_order(alpha)})")
print(f"Generator β = {beta}  (x ↦ 2x mod 7, order {perm_order(beta)})")

# Generate the full group by taking all products
def generate_group(generators):
    identity = tuple(range(7))
    group = {identity}
    frontier = set(generators)
    group.update(frontier)
    
    while frontier:
        new_frontier = set()
        for g in list(group):
            for gen in generators:
                for product in [compose(g, gen), compose(gen, g), 
                               compose(g, inverse_perm(gen)), compose(inverse_perm(gen), g)]:
                    if product not in group:
                        new_frontier.add(product)
                        group.add(product)
        frontier = new_frontier
    return group

# First generate F₂₁ = ⟨α, β⟩ (affine group)
F21 = generate_group([alpha, beta])
print(f"\n|F₂₁| = |⟨α, β⟩| = {len(F21)}")

# For PSL(2,7) we need an additional generator
# γ = x ↦ -1/x mod 7, which is the inversion
# -1/x mod 7: 1↦6, 2↦3 (since 2*4=8≡1, -4≡3), 3↦5 (3*5=15≡1, -5≡2... wait)
# Let me compute: -1/x mod 7
# x=1: -1/1 = -1 ≡ 6
# x=2: -1/2 ≡ -4 ≡ 3 (since 2⁻¹ = 4 mod 7)
# x=3: -1/3 ≡ -5 ≡ 2 (since 3⁻¹ = 5 mod 7)
# x=4: -1/4 ≡ -2 ≡ 5 (since 4⁻¹ = 2 mod 7)
# x=5: -1/5 ≡ -3 ≡ 4 (since 5⁻¹ = 3 mod 7)
# x=6: -1/6 ≡ -6 ≡ 1 (since 6⁻¹ = 6 mod 7)
# x=0: undefined (maps to ∞)
# So γ = (1 6)(2 3)(4 5) on {1,...,6}, but 0 is a fixed point? No, 0 maps to ∞.
# For the 7-point action we need a different approach.

# Actually, PSL(2,7) has a faithful action on 7 points via its action on 
# the 7 points of the Fano plane. Let me use a known permutation representation.
# 
# From the ATLAS: PSL(2,7) on 7 points is generated by
# a = (0 1 2 3 4 5 6) and b = (1 2 4)(3 6 5)
# Wait — these are exactly α and β but β should be (1 2 4)(3 6 5).

# Let me recheck β
beta2 = [0, 2, 4, 6, 1, 3, 5]  # x ↦ 2x mod 7
# 0↦0, 1↦2, 2↦4, 3↦6, 4↦1, 5↦3, 6↦5
# As cycles: (1 2 4)(3 6 5)
print(f"β as cycles: (1 2 4)(3 6 5)")

# For PSL(2,7), we need a third generator that's NOT in the affine group
# The standard choice: the inversion x ↦ -1/x needs to be modified for 7-point action
# Let's use: γ swaps 0 ↔ ∞ in the P¹ action, restricted to 7 points

# Alternative: use the presentation of PSL(2,7) from the literature
# PSL(2,7) ≅ GL(3, F₂) ≅ Aut(Fano plane)
# On 7 points, it's generated by a = (0 1 2 3 4 5 6) and b = (1 2)(3 6)
# Let's try this

gamma = list(range(7))
# (1 6)(2 3)(4 5)
gamma[1], gamma[6] = 6, 1
gamma[2], gamma[3] = 3, 2
gamma[4], gamma[5] = 5, 4
gamma = tuple(gamma)
print(f"\nAdditional generator γ = {gamma}  (order {perm_order(gamma)})")

PSL27 = generate_group([alpha, beta, gamma])
print(f"|PSL(2,7)| = |⟨α, β, γ⟩| = {len(PSL27)}")

if len(PSL27) == 168:
    print("★ Confirmed: |PSL(2,7)| = 168 = |Aut(Fano)|")
elif len(PSL27) == 5040:
    print("Got full S₇ — γ is not in PSL(2,7), trying different generator")
else:
    print(f"Got group of order {len(PSL27)} — checking...")

# If we didn't get 168, try alternative generators
if len(PSL27) != 168:
    # Try: PSL(2,7) on 7 points generated by (0123456) and (124)(365)
    # which is the standard from many sources
    beta3 = [0, 2, 4, 6, 1, 3, 5]  # (1 2 4)(3 6 5) = x ↦ 2x mod 7
    
    # Add the element corresponding to x ↦ 3x+1 or similar
    # Actually let's just use a brute force approach: find ALL permutations
    # that preserve the unoriented Fano plane (not requiring orientation preservation)
    
    fano_lines = [
        frozenset({0, 1, 3}),
        frozenset({1, 2, 4}),
        frozenset({2, 3, 5}),
        frozenset({3, 4, 6}),
        frozenset({4, 5, 0}),
        frozenset({5, 6, 1}),
        frozenset({6, 0, 2}),
    ]
    
    PSL27_direct = set()
    for perm in permutations(range(7)):
        preserves = True
        for line in fano_lines:
            mapped = frozenset(perm[i] for i in line)
            if mapped not in fano_lines:
                preserves = False
                break
        if preserves:
            PSL27_direct.add(perm)
    
    print(f"\nDirect computation: permutations preserving unoriented Fano lines = {len(PSL27_direct)}")
    PSL27 = PSL27_direct

print(f"\nFinal: |Aut(Fano)| = {len(PSL27)}")

# ================================================================
# PART 2: Compute dim(Λ³ℝ⁷)^{PSL(2,7)}
# ================================================================
print("\n--- PART 2: PSL(2,7)-Invariant 3-Forms on ℝ⁷ ---\n")

# A 3-form ω ∈ Λ³(ℝ⁷) has C(7,3) = 35 independent components
# ω_{ijk} for i < j < k
# σ ∈ S₇ acts on ω by σ·ω_{ijk} = sgn(σ restricted to {i,j,k} ↦ {σi,σj,σk}) · ω_{σi,σj,σk}
# (with indices reordered to be increasing)

# A 3-form is PSL(2,7)-invariant if σ·ω = ω for all σ ∈ PSL(2,7)
# This means: for each σ, and each triple i<j<k,
# ω_{σ(i),σ(j),σ(k)} (with appropriate sign) = ω_{ijk}

# Build the 35 triples
triples = []
for i in range(7):
    for j in range(i+1, 7):
        for k in range(j+1, 7):
            triples.append((i, j, k))

n_triples = len(triples)
triple_index = {t: idx for idx, t in enumerate(triples)}

def sorted_triple_sign(a, b, c):
    """Sort three indices and return (sorted_triple, sign)"""
    trip = [a, b, c]
    sign = 1
    # Bubble sort to count transpositions
    for i in range(3):
        for j in range(i+1, 3):
            if trip[i] > trip[j]:
                trip[i], trip[j] = trip[j], trip[i]
                sign *= -1
    return tuple(trip), sign

# For each σ ∈ PSL(2,7), build the 35×35 matrix representing its action on Λ³
# Then the invariant subspace is the intersection of all eigenspaces for eigenvalue 1
# Equivalently: average the matrices and find the rank of the average

avg_matrix = np.zeros((n_triples, n_triples))

for sigma in PSL27:
    mat = np.zeros((n_triples, n_triples))
    for idx, (i, j, k) in enumerate(triples):
        si, sj, sk = sigma[i], sigma[j], sigma[k]
        sorted_trip, sign = sorted_triple_sign(si, sj, sk)
        target_idx = triple_index[sorted_trip]
        mat[target_idx, idx] = sign
    avg_matrix += mat

avg_matrix /= len(PSL27)

# The rank of avg_matrix = dimension of the invariant subspace
rank = np.linalg.matrix_rank(avg_matrix, tol=1e-8)
print(f"dim(Λ³ℝ⁷)^{{PSL(2,7)}} = {rank}")
print()

if rank == 1:
    print("★★★ PSL(2,7)-INVARIANCE UNIQUELY DETERMINES THE G₂ 3-FORM ★★★")
    print()
    print("The full Fano automorphism group (order 168) pins down φ up to scale.")
    print("This means:")
    print("  - ANY 3-form on ℝ⁷ invariant under all 168 Fano symmetries is a")
    print("    scalar multiple of the G₂ associative 3-form φ")
    print("  - The G₂ structure is FORCED by the combinatorial symmetry of the")
    print("    Fano plane — you don't need to know about octonions!")
    print("  - The 168 identity (168 = 14 × 2 × 6) is the bridge:")
    print("    PSL(2,7) lives in BOTH S₇ (permuting outcomes) and G₂ (preserving φ)")
    print("  - The Fisher-Rao metric has S₇ symmetry, hence PSL(2,7) symmetry")
    print("  - PSL(2,7) forces φ, hence forces G₂ geometry")
    print("  - THE BRIDGE: S₇ symmetry of probability → PSL(2,7) → G₂ structure")
    
    # Find the invariant 3-form
    eigenvalues, eigenvectors = np.linalg.eigh(avg_matrix)
    # The invariant subspace corresponds to eigenvalue 1 of avg_matrix
    # (avg_matrix is a projector, so eigenvalues are 0 or 1)
    invariant_idx = np.where(np.abs(eigenvalues - 1.0) < 1e-8)[0]
    if len(invariant_idx) == 1:
        v = eigenvectors[:, invariant_idx[0]]
        v = v / np.max(np.abs(v))  # Normalize so max component is ±1
        print("\nThe unique PSL(2,7)-invariant 3-form (up to scale):")
        print("Components on triples (i,j,k) with i<j<k:")
        for idx, (i, j, k) in enumerate(triples):
            if abs(v[idx]) > 1e-8:
                print(f"  ω({i},{j},{k}) = {v[idx]:+.6f}")
        
        # Check if this matches the G₂ 3-form
        phi_vec = np.zeros(n_triples)
        fano_oriented = [(0,1,3), (1,2,4), (2,3,5), (3,4,6), (0,4,5), (1,5,6), (0,2,6)]
        for (a,b,c) in fano_oriented:
            st, sg = sorted_triple_sign(a, b, c)
            phi_vec[triple_index[st]] = sg
        
        phi_vec_norm = phi_vec / np.max(np.abs(phi_vec))
        
        # Check proportionality
        ratio = None
        is_proportional = True
        for idx in range(n_triples):
            if abs(phi_vec[idx]) > 1e-8 and abs(v[idx]) > 1e-8:
                r = v[idx] / phi_vec[idx]
                if ratio is None:
                    ratio = r
                elif abs(r - ratio) > 1e-6:
                    is_proportional = False
                    break
            elif abs(phi_vec[idx]) > 1e-8 or abs(v[idx]) > 1e-8:
                is_proportional = False
                break
        
        if is_proportional and ratio is not None:
            print(f"\n★ CONFIRMED: The invariant 3-form is proportional to φ (ratio = {ratio:.6f})")
            print("★ PSL(2,7) uniquely determines the G₂ structure!")
        else:
            print(f"\nThe invariant form does NOT match φ — checking...")

elif rank == 2:
    print("dim = 2: PSL(2,7) almost pins down φ (1 free parameter)")
    print("Close but not unique. The G₂ form is in a 1-parameter family.")
    
elif rank == 3:
    print("dim = 3: Same as F₂₁ — PSL(2,7) doesn't help beyond F₂₁")
    
else:
    print(f"dim = {rank}")

# ================================================================
# PART 3: Cross-check with F₂₁
# ================================================================
print(f"\n--- PART 3: Comparison ---\n")

# Also compute for F₂₁
avg_F21 = np.zeros((n_triples, n_triples))
for sigma in F21:
    mat = np.zeros((n_triples, n_triples))
    for idx, (i, j, k) in enumerate(triples):
        si, sj, sk = sigma[i], sigma[j], sigma[k]
        sorted_trip, sign = sorted_triple_sign(si, sj, sk)
        target_idx = triple_index[sorted_trip]
        mat[target_idx, idx] = sign
    avg_F21 += mat
avg_F21 /= len(F21)

rank_F21 = np.linalg.matrix_rank(avg_F21, tol=1e-8)
print(f"dim(Λ³ℝ⁷)^{{F₂₁}} = {rank_F21}  (Claude computed 3)")
print(f"dim(Λ³ℝ⁷)^{{PSL(2,7)}} = {rank}  (our new result)")
print()
if rank < rank_F21:
    print(f"PSL(2,7) is MORE constraining than F₂₁: {rank} < {rank_F21}")
if rank == 1:
    print("PSL(2,7) is maximally constraining: UNIQUE invariant 3-form")

